dist: xenial
services:
  - xvfb

language: php

sudo: required

 # Downloaded browsers will be cached in selenium-assistant by
 # web-push-testing-service. Caching will speed up build time.
cache:
  directories:
    - ~/.selenium-assistant
    - node_modules                  # cache modules too
    - $HOME/.composer/cache/files   # and composer packages

addons:
  chrome: stable
  firefox: latest

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: nightly

env:
  - TRAVIS_NODE_VERSION="stable"

before_install:
  - nvm install node

install:
  - npm install github:GoogleChromeLabs/web-push-testing-service#38671ab2e2a1c9857059614064c05c4db8e2e75c -g

before_script:
  - composer install --prefer-source -n

script:
  - web-push-testing-service start example -p 9012
  - composer test:unit
  - web-push-testing-service stop example
  - composer test:typing
  - composer test:syntax
